name: bayesian-hierarchical-clustering
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy>=1.26.0,<2.0
  - scipy>=1.13.0
  - pip
  - pip:
    - build>=0.10.0
    - flake8
    - coverage
    - pytest
